navbar-styled
swapnilsparsh/DevEmpire pull request #133
Opened 2022-05-14 12:28 UTC by mayank-del

fixes #107 

added awesome hover to navbar.

2022-05-14 18:32 UTC, swapnilsparsh requested changes
Change the UI of Navbar not just the effect on hover.

2022-05-17 12:39 UTC, mayank-del commented
> @swapnilsparsh sir, please merge it, So that I would start working on other projects as soon as possible.

@swapnilsparsh sir, please try to understand, time is very less

2022-05-18 02:14 UTC, mayank-del commented
> > @swapnilsparsh sir, please merge it, So that I would start working on other projects as soon as possible.
> 
> @swapnilsparsh sir, please try to understand, time is very less

@swapnilsparsh sir are you there??

2022-05-18 18:12 UTC, swapnilsparsh commented
> > > @swapnilsparsh sir, please merge it, So that I would start working on other projects as soon as possible.
> > 
> > @swapnilsparsh sir, please try to understand, time is very less
> 
> @swapnilsparsh sir are you there??

It's not appropriate as you have changes the color scheme of the navbar and also didn't designed the navbar as there will be more headings in future.

2022-05-18 18:16 UTC, mayank-del commented
> > > > @swapnilsparsh sir, please merge it, So that I would start working on other projects as soon as possible.
> > > 
> > > 
> > > @swapnilsparsh sir, please try to understand, time is very less
> > 
> > 
> > @swapnilsparsh sir are you there??
> 
> It's not appropriate as you have changes the color scheme of the navbar and also didn't designed the navbar as there will be more headings in future.

ok wait, i am making it same as previous color

2022-05-18 18:17 UTC, swapnilsparsh commented
> > > > > @swapnilsparsh sir, please merge it, So that I would start working on other projects as soon as possible.
> > > > 
> > > > 
> > > > @swapnilsparsh sir, please try to understand, time is very less
> > > 
> > > 
> > > @swapnilsparsh sir are you there??
> > 
> > It's not appropriate as you have changes the color scheme of the navbar and also didn't designed the navbar as there will be more headings in future.
> 
> ok wait, i am making it same as previous color

You have to change the design also as I have mentioned it in issue before hand.

2022-05-18 19:06 UTC, mayank-del commented
@swapnilsparsh sir , are you there,I  Increase it's size and make linear-gradients of blue,If you want too much enhancement , I will suggest you as developer , don't do this ,Your navbar is looking really cool , we should focus on body which is not good

2022-05-21 02:26 UTC, mayank-del commented
@swapnilsparsh  sir, please see the change, i have  made it 3 days earlier,tell me it is fine or not, 
If it doesn't seems fine to you , then give any UI or link of any website which you like .Else even if, I will style it many times , you will reject it. So, please suggest any UI.

2022-05-22 08:40 UTC, swapnilsparsh commented
> @swapnilsparsh sir, please see the change, i have made it 3 days earlier,tell me it is fine or not, If it doesn't seems fine to you , then give any UI or link of any website which you like .Else even if, I will style it many times , you will reject it. So, please suggest any UI.

https://www.toools.design/

Design the Navbar like this, simple and clean.
Do the CSS in the SASS file and follow the color scheme.

2022-05-22 14:00 UTC, mayank-del commented
@swapnilsparsh  sir , please check it, I think it is fine now

2022-05-24 23:11 UTC, mayank-del commented
@swapnilsparsh , sir please tell me me sir,is this ok??
 i have to work on next issue in this repo

2022-05-24 23:12 UTC, mayank-del commented
@swapnilsparsh sir,please response

2022-05-25 08:50 UTC, swapnilsparsh commented
@mayank-del Some changes are required:
1. Remove the shadow which you have added in the navbar
2. Move the Hamburger icon right side and add the text "DevEmpire on the left side"
3. Use flexbox and flex-wrap as column preference is not required if space is there.

**Do all the CSS work in the SASS file, not in the CSS file, and use sass live compiler from vs code extension.**

2022-05-25 12:07 UTC, mayank-del commented
@swapnilsparsh sir, check it ,I have done required changes.

2022-05-26 05:38 UTC, swapnilsparsh commented
> @swapnilsparsh sir, check it ,I have done required changes.

Align all the titles of the navbar in one line and for mobile view, all the titles should be in an aligned center
Use Live SASS Compiler for styling which you can find in VS Code Extension.

2022-05-26 13:38 UTC, mayank-del commented
@swapnilsparsh  sir , now I did each and every instruction given by you.

2022-05-26 13:45 UTC, swapnilsparsh commented
> @swapnilsparsh  sir , now I did each and every instruction given by you.
> now you can merge it.

Align all the titles of the navbar in one line and for mobile view, all the titles should be in an aligned center

2022-05-26 14:20 UTC, mayank-del commented
> > @swapnilsparsh  sir , now I did each and every instruction given by you.
> > now you can merge it.
> 
> Align all the titles of the navbar in one line and for mobile view, all the titles should be in an aligned center

All are are in one line , I made flex , but only in scss as told by

2022-05-26 14:21 UTC, swapnilsparsh commented
> > > @swapnilsparsh  sir , now I did each and every instruction given by you.
> > > now you can merge it.
> > 
> > Align all the titles of the navbar in one line and for mobile view, all the titles should be in an aligned center
> 
> @swapnilsparsh  sir,
> All are are in one line , I made flex , but only in scss as told by you.

You haven't use the SASS live compiler also.

2022-05-26 14:22 UTC, mayank-del commented
> > > > @swapnilsparsh  sir , now I did each and every instruction given by you.
> > > > now you can merge it.
> > > 
> > > 
> > > Align all the titles of the navbar in one line and for mobile view, all the titles should be in an aligned center
> > 
> > 
> > @swapnilsparsh  sir,
> > All are are in one line , I made flex , but only in scss as told by you.
> 
> You haven't use the SASS live compiler also.

Now check it,

2022-05-26 14:25 UTC, mayank-del commented
![IMG_20220526_195312](https://user-images.githubusercontent.com/82238106/170507884-cbd90f71-26fa-4fcf-ad92-a811303275a4.jpg)


@swapnilsparsh  sir, check styling is target by scss instead of  css

2022-05-26 14:28 UTC, mayank-del commented
![Screenshot 2022-05-26 195719](https://user-images.githubusercontent.com/82238106/170508669-524ecb14-57b9-44c2-97d0-f48b8b85f3fd.png)

mobile view

2022-05-26 14:30 UTC, mayank-del commented
![Screenshot 2022-05-26 195936](https://user-images.githubusercontent.com/82238106/170509047-a4df982f-6772-474e-a381-fedeb2b5b7e2.png)

Desktop View

2022-05-26 17:48 UTC, swapnilsparsh requested changes
1. The desktop version is fine.
2. In mobile view all the headings should be aligned center.
3. You have hard-coded the CSS code instead of using the SASS, fix it.

2022-05-26 18:12 UTC, mayank-del commented
> 1. The desktop version is fine.
> 2. In mobile view all the headings should be aligned center.
> 3. You have hard-coded the CSS code instead of using the SASS, fix it.

@swapnilsparsh  sir, can you explain the 3rd point. I am not getting it

2022-05-26 18:23 UTC, swapnilsparsh commented
> > 1. The desktop version is fine.
> > 2. In mobile view all the headings should be aligned center.
> > 3. You have hard-coded the CSS code instead of using the SASS, fix it.
> 
> @swapnilsparsh sir, can you explain the 3rd point. I am not getting it. Do you want me reverse the changes of css file to initial state and let scss to control the global styling??

Have a look [here](https://github.com/swapnilsparsh/DevEmpire/blob/master/CONTRIBUTING.md#need-some-help-regarding-the-basics=)
You have to reverse the changes from the CSS file and do all the CSS code in the SASS file then use the SASS Live Compiler to automatically convert the code to CSS.

2022-05-27 08:21 UTC, mayank-del commented
@swapnilsparsh sir, Very sorry for inconvenience , I understood what you want to say , now i compiled sass code into css using compiler, you can check the package.json and also aligned items to center for mobile view.

2022-05-27 18:29 UTC, mayank-del commented
@

> @swapnilsparsh sir, Very sorry for inconvenience , I understood what you want to say , now i compiled sass code into css using compiler, you can check the package.json and also aligned items to center for mobile view.

@swapnilsparsh  sir, merge it so that , I will finish next work also.

2022-05-28 02:36 UTC, mayank-del commented
> @
> 
> > @swapnilsparsh sir, Very sorry for inconvenience , I understood what you want to say , now i compiled sass code into css using compiler, you can check the package.json and also aligned items to center for mobile view.
> 
> @swapnilsparsh sir, merge it so that , I will finish next work also.

@swapnilsparsh sir, I have completed everything told by you,.

2022-05-28 11:44 UTC, mayank-del commented
@swapnilsparsh  please check now,I understood the issue and fixed that, now you should merge

2022-05-29 05:52 UTC, swapnilsparsh commented on package.json
>    },
Why you have added extra lines here?

2022-05-29 05:54 UTC, swapnilsparsh requested changes
Tell?

2022-05-29 05:54 UTC, swapnilsparsh commented on pages/_app.js
> +import "../styles/globals.css";
Why you have changed the styling from SASS to CSS?

2022-05-29 05:54 UTC, swapnilsparsh commented on package.json
> +    "compile:sass":"sass styles/globals.scss styles/globals.css"
Why you have added an extra line here?

2022-05-29 05:54 UTC, swapnilsparsh commented on package.json
> +    "scss": "^0.2.4"
What is the need for extra dependencies here?

2022-05-29 18:01 UTC, mayank-del commented
@swapnilsparsh , You have made your code written on scss, what u asked me to do is to compile scss code in css by vs code extension, hence I made undo my mistake of importing scss instead of compiles css as told by you .

2022-05-29 18:02 UTC, mayank-del commented
@swapnilsparsh , dependencies was my mistake , very sorry for that, I uninstalled those scss and sass dependencies,

Now ,it is fine , you should merge it

2022-05-29 18:07 UTC, mayank-del commented on package.json
> +    "compile:sass":"sass styles/globals.scss styles/globals.css"
Now , I removed that  line from package.json, I added that line to compile my scss written code to css with help of sass compiler present in vs code , but now it is not present

2022-05-29 18:09 UTC, mayank-del commented on package.json
> +    "scss": "^0.2.4"
Sorry , it was my mistake, I installed those by mistake , I uninstalled those dependencies , Now u can merge it.

2022-05-29 18:10 UTC, mayank-del commented on pages/_app.js
> +import "../styles/globals.css";
@swapnilsparsh , You have made your code written on scss, what u asked me to do is to compile scss code in css by vs code extension, hence I made undo my mistake of importing scss instead of compiles css as told by you .

2022-05-30 12:58 UTC, mayank-del commented
@swapnilsparsh  sir now check and merge, only one day is remaining, I completed every work.

2022-05-30 16:40 UTC, swapnilsparsh requested changes
I appreciate your time and efforts but if the PR will not be of up to the mark then it will not be merged until all the chamges has been done correctly.

2022-05-30 16:40 UTC, swapnilsparsh commented on components/navbar/Links.js
>              setmenuopen(true);
Why use of console.log has been done here as it was not required?

2022-05-30 16:40 UTC, swapnilsparsh commented on components/navbar/Links.js
>              setmenuopen(false);
Why use of console.log has been done here as it was not required.

2022-05-30 17:21 UTC, mayank-del commented
> I appreciate your time and efforts but if the PR will not be of up to the mark then it will not be merged until all the chamges has been done correctly.

@swapnilsparsh  sir, very sorry for such things, Now check it ,  I removed both.

2022-05-31 14:18 UTC, swapnilsparsh requested changes

2022-05-31 14:18 UTC, swapnilsparsh commented on components/navbar/Links.js
> +      <div className="x-button"
There was no need of creating an extra className as it will take time in processing the code.

2022-06-01 12:00 UTC, swapnilsparsh commented
> @swapnilsparsh i have tried many alternate ways , but your initial codes didn't allowed me to do so .

According to the code structure, it was very well possible.

2022-06-01 17:40 UTC, mayank-del commented
@swapnilsparsh sir, i have tried to do at that time, but I couldn't, but just because of one extra class you haven't merged

2022-06-03 05:00 UTC, swapnilsparsh commented
> @swapnilsparsh sir, i have tried to do at that time, but I couldn't, but just because of one extra class you haven't merged

I haven't asked you to make the new class as it was possible in the old class only.

2022-06-03 05:00 UTC, closed without merging